# Generated by Django 3.1.6 on 2021-05-22 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(default='1', editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='cholele', max_length=45)),
                ('lastname', models.CharField(default='hernandez', max_length=55)),
                ('semestre', models.IntegerField(blank=True, default=2, null=True)),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('correo', models.CharField(blank=True, max_length=60, null=True)),
                ('clave', models.CharField(default='1234', max_length=35)),
                ('fecha_nac', models.DateField(default=datetime.date.today)),
                ('Genero', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Facultad', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_intercambio', models.CharField(max_length=12)),
                ('universidad_destino', models.CharField(max_length=55)),
                ('periodo', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('tipo', models.TextField(max_length=45)),
                ('descripcion', models.TextField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(default='Movilidad en España', max_length=920)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('vistas', models.IntegerField(default='1')),
                ('Alumno_idAlumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='era.alumno')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_multimedia', models.CharField(default='1', max_length=120)),
                ('url', models.CharField(max_length=150, null=True)),
                ('tipo', models.CharField(max_length=45, null=True)),
                ('Publicacion_idPublicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='era.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comentario', models.CharField(default='1', max_length=120)),
                ('Comentario', models.CharField(max_length=750, null=True)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='era.alumno')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrera', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=45)),
                ('abreviado', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('Facultad_idFacultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='era.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Carrera_idCarrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='era.carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Intercambio_idintercambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='era.intercambio'),
        ),
    ]
