# Generated by Django 3.1.6 on 2021-04-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=55)),
                ('semestre', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=35)),
                ('fecha_nac', models.DateTimeField()),
                ('Genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('abreviado', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Comentario', models.CharField(max_length=750)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_Facultad', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id_intercambio', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('universidad_destino', models.CharField(max_length=55)),
                ('periodo', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id_multimedia', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=920)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('vistas', models.IntegerField()),
            ],
        ),
    ]
