# Generated by Django 3.2 on 2021-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=55)),
                ('semestre', models.IntegerField()),
                ('telefono', models.CharField(max_length=9)),
                ('correo', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=35)),
                ('fecha_nac', models.DateTimeField()),
                ('Genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_Facultad', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id_intercambio', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('universidad_destino', models.CharField(max_length=55)),
                ('periodo', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=920)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('vistas', models.IntegerField()),
                ('Alumno_idAlumno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id_multimedia', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=45)),
                ('Publicacion_idPublicacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Comentario', models.CharField(max_length=750)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('Alumno_idalumno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('abreviado', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('Facultad_idFacultad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Carrera_idCarrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Intercambio_idintercambio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.intercambio'),
        ),
    ]
