# Generated by Django 3.1.6 on 2021-05-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Carrera_idCarrera',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Intercambio_idintercambio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.intercambio'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='Facultad_idFacultad',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.facultad'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='Alumno_idalumno',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.alumno'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='Publicacion_idPublicacion',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.publicacion'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='Alumno_idAlumno',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='era.alumno'),
        ),
    ]
