# Generated by Django 3.1.6 on 2021-04-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='Facultad_idFacultad',
            field=models.ForeignKey(default='DEFAULT-VALUE', on_delete=django.db.models.deletion.CASCADE, to='era.facultad'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='id_Facultad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
