# Generated by Django 3.1.6 on 2021-05-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='era.publicacion'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_alumno',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id_comentario',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
