# Generated by Django 3.1.6 on 2021-04-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0002_auto_20210409_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='Carrera_idCarrera',
            field=models.ForeignKey(default='DEFAULT-VALUE', on_delete=django.db.models.deletion.CASCADE, to='era.carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Intercambio_idintercambio',
            field=models.ForeignKey(default='DEFAULT-VALUE', on_delete=django.db.models.deletion.CASCADE, to='era.intercambio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='Alumno_idalumno',
            field=models.ForeignKey(default='DEFAULT-VALUE', on_delete=django.db.models.deletion.CASCADE, to='era.alumno'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='Publicacion_idPublicacion',
            field=models.ForeignKey(default='DEFAULT-VALUE', on_delete=django.db.models.deletion.CASCADE, to='era.publicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='Alumno_idAlumno',
            field=models.ForeignKey(default='DEFAULT-VALUE', on_delete=django.db.models.deletion.CASCADE, to='era.alumno'),
        ),
    ]
