# Generated by Django 3.1.6 on 2021-04-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0003_auto_20210409_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Facultad_idFacultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='era.facultad'),
        ),
    ]
