# Generated by Django 3.1.6 on 2021-05-21 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('era', '0003_publicacion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(default='1'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='hora',
            field=models.TimeField(default='1'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
