# Generated by Django 3.1.6 on 2021-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0004_auto_20210521_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='hora',
            field=models.IntegerField(default='1'),
        ),
    ]
