# Generated by Django 3.1.6 on 2021-05-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0006_auto_20210521_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='user',
            new_name='User',
        ),
    ]
