# Generated by Django 3.1.6 on 2021-05-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0007_auto_20210521_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='User',
            new_name='user',
        ),
    ]
