# Generated by Django 3.1.6 on 2021-05-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0012_auto_20210521_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='Alumno_idAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='era.alumno'),
        ),
    ]
