# Generated by Django 3.1.6 on 2021-05-21 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0015_auto_20210521_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='hora',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
