# Generated by Django 3.1.6 on 2021-05-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0016_auto_20210521_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='Carrera_idCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='era.carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='Intercambio_idintercambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='era.intercambio'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='Alumno_idalumno',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='era.alumno'),
        ),
    ]
