# Generated by Django 3.1.6 on 2021-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('era', '0018_auto_20210521_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Alumno_idalumno',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', related_query_name='alumno', to='era.alumno'),
        ),
    ]
